### ISSUE TITLE
Patched python3.11 sysconfig.py breaks some usecases

### ISSUE THREAD

**Issue by m-khvoinitsky** [Homebrew/formula-patches#880] opened 2023-02-22 13:35 UTC
I have a code which gives me path to `site-packages` of a venv which works great on all OSes:
```python
def venv_site_packages(venv_path):
    return os.path.realpath(sysconfig.get_path('purelib', expand=True, vars={'base': venv_path}))
```
However, it's broken on python3.11 on macOS installed from Homebrew. Debugging has led me to this repo with patches. 
related commit: https://github.com/Homebrew/formula-patches/commit/6d2fba8de3159182025237d373a6f4f78b8bd203

**Comment by m-khvoinitsky** [comment] 2023-03-16 14:10
Summoning some attention, @Bo98.

**Comment by carlocab** [comment] 2023-03-18 17:29
Duplicate of Homebrew/homebrew-core#120032

**Closed by carlocab** 2023-03-18 17:29 UTC
